fixed some syntax

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -69,9 +69,9 @@ jobs:
           # Navigate to project path
           echo "Navigating to $VPS_PATH"
 
-          if [ -z "$VPS_PATH"]; then
-            echo "Error: VPS_PATH is empty"
-            exit 1
+          if [ -z "$VPS_PATH" ]; then
+              echo "Error: VPS_PATH is empty"
+              exit 1
           fi
 
           cd $VPS_PATH || { echo "Error: $VPS_PATH does not exist"; exit 1; }
